package view;

  
import java.awt.Color;
import model.Account;
import java.util.*;
import java.text.NumberFormat;
import javax.swing.table.DefaultTableModel;
import model.Share;



/** 
 * @author Diego Schmaedech
 * @version 1.1
 * @since Release Carnaval
 * @link  https://github.com/schmaedech/expecon
 * Created on August 2, 2008, 2:34 AM
 */
public class AccountView extends AbstractAccountView {

    private NumberFormat moneyFormat = NumberFormat.getCurrencyInstance( Locale.US );
    private double openingMoney = 0.0; 
    private double moneyBalance = 0.0; 
    private Share share;
    /** Creates new form AccountView */
    public AccountView(Account account, Share share) {
        super( account );
        setShare(share);
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfOpeningMoney = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfMoneyBalance = new javax.swing.JTextField();
        jtbExtract = new javax.swing.JTabbedPane();
        jspPeriodReview = new javax.swing.JScrollPane();
        jtPeriodReview = new javax.swing.JTable();
        jspShareBalance = new javax.swing.JScrollPane();
        jtShareBalance = new javax.swing.JTable();

        setBackground(new java.awt.Color(254, 254, 254));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(AccountView.class, "AccountView.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans 13", 1, 12), new java.awt.Color(113, 196, 243))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(jPanel1.getFont());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+1));
        jLabel1.setText("Budget:"); // NOI18N

        jtfOpeningMoney.setEditable(false);
        jtfOpeningMoney.setColumns(10);
        jtfOpeningMoney.setFont(jtfOpeningMoney.getFont().deriveFont(jtfOpeningMoney.getFont().getSize()+1f));
        jtfOpeningMoney.setText(moneyFormat.format( getAccount().getOpeningMoney() ));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+1));
        jLabel3.setText("Total Balance:"); // NOI18N

        jtfMoneyBalance.setEditable(false);
        jtfMoneyBalance.setColumns(10);
        jtfMoneyBalance.setFont(jtfMoneyBalance.getFont());
        jtfMoneyBalance.setText(moneyFormat.format( getAccount().getMoneyBalance() ));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfMoneyBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOpeningMoney))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfOpeningMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMoneyBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbExtract.setBackground(new java.awt.Color(255, 255, 255));
        jtbExtract.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jtbExtract.setFont(jtbExtract.getFont().deriveFont(jtbExtract.getFont().getStyle() | java.awt.Font.BOLD));
        jtbExtract.setMinimumSize(new java.awt.Dimension(0, 0));
        jtbExtract.setPreferredSize(new java.awt.Dimension(600, 200));

        jspPeriodReview.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jtPeriodReview.setAutoCreateRowSorter(true);
        jtPeriodReview.setFont(jtPeriodReview.getFont());
        jtPeriodReview.setModel(new DefaultTableModel(getShare().getHistoryData(), getShare().getHistoryHeader()));
        jtPeriodReview.setFillsViewportHeight(true);
        jtPeriodReview.setGridColor(new java.awt.Color(113,196,243));
        jtPeriodReview.setPreferredSize(new java.awt.Dimension(200, 100));
        jtPeriodReview.setRowSelectionAllowed(false);
        jtPeriodReview.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jspPeriodReview.setViewportView(jtPeriodReview);

        jtbExtract.addTab(org.openide.util.NbBundle.getMessage(AccountView.class, "AccountView.jspPeriodReview.TabConstraints.tabTitle"), jspPeriodReview); // NOI18N

        jtShareBalance.setAutoCreateRowSorter(true);
        jtShareBalance.setModel(new DefaultTableModel(getAccount().getExtractData(), getAccount().getExtractHeader()));
        jtShareBalance.setEnabled(false);
        jtShareBalance.setFillsViewportHeight(true);
        jtShareBalance.setGridColor(new java.awt.Color(113,196,243));
        jtShareBalance.setPreferredSize(new java.awt.Dimension(600, 200));
        jspShareBalance.setViewportView(jtShareBalance);

        jtbExtract.addTab(org.openide.util.NbBundle.getMessage(AccountView.class, "AccountView.jspShareBalance.TabConstraints.tabTitle"), jspShareBalance); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jtbExtract, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbExtract, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtbExtract.getAccessibleContext().setAccessibleName("Carteira de Ativos"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspPeriodReview;
    private javax.swing.JScrollPane jspShareBalance;
    private javax.swing.JTable jtPeriodReview;
    private javax.swing.JTable jtShareBalance;
    private javax.swing.JTabbedPane jtbExtract;
    private javax.swing.JTextField jtfMoneyBalance;
    private javax.swing.JTextField jtfOpeningMoney;
    // End of variables declaration//GEN-END:variables
    
    
    public void setShare(Share share) {
        this.share = share;
    }
 
     
    public Share getShare() {
        return share;
    }
    
    @Override
    public void updateDisplay() {
        jtShareBalance.setModel(new DefaultTableModel(getAccount().getExtractData(), getAccount().getExtractHeader()));
        jtPeriodReview.setModel(new DefaultTableModel(getShare().getHistoryData(), getShare().getHistoryHeader()));
        
        openingMoney = getAccount().getOpeningMoney();
        moneyBalance = getAccount().getMoneyBalance();
        if(openingMoney < 0  ){
            jtfOpeningMoney.setText( moneyFormat.format( openingMoney ) );
            jtfOpeningMoney.setBackground(new Color(225,0,0)); 
        }else{
            jtfOpeningMoney.setText( moneyFormat.format( openingMoney ) );
            jtfOpeningMoney.setBackground(new Color(225,225,225)); 
        }
        if( moneyBalance < 0){
            jtfMoneyBalance.setText( moneyFormat.format( moneyBalance ) );
            jtfMoneyBalance.setBackground(new Color(225,0,0));
        }else{  
            jtfMoneyBalance.setText( moneyFormat.format( moneyBalance ) );
            jtfMoneyBalance.setBackground(new Color(225,225,225));
        }
  }
}
