package view;


import model.Share;
  
/** 
 * @author Diego Schmaedech
 * @version 1.1
 * @since Release Carnaval
 * @link  https://github.com/schmaedech/expecon
 * Created on August 2, 2008, 2:34 AM
 */
public class ShareView extends AbstractShareView {

      
    /** Creates new form ShareView
     * @param share 
     */
    public ShareView( Share share ) {
        super( share ); 
         
        initComponents();
        loadTableModel();
        updateDisplay();
    }
    
     
    public void loadTableModel(){
        jtShare.setModel(new javax.swing.table.DefaultTableModel(
            getShare().getAvaliableShares(),
            getShare().getParams()
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspMarketShare = new javax.swing.JScrollPane();
        jtShare = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(398, 200));
        setLayout(new java.awt.GridLayout(1, 0));

        jspMarketShare.setBackground(new java.awt.Color(254, 254, 254));

        jtShare.setAutoCreateRowSorter(true);
        jtShare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ativo", "Preço", "Cor", "Variação", "Periodo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtShare.setCellSelectionEnabled(true);
        jtShare.setGridColor(new java.awt.Color(153, 153, 153));
        jtShare.setPreferredSize(new java.awt.Dimension(398, 198));
        jspMarketShare.setViewportView(jtShare);
        jtShare.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jspMarketShare);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspMarketShare;
    private javax.swing.JTable jtShare;
    // End of variables declaration//GEN-END:variables
    public void updateDisplay() {
       loadTableModel(); 
   }
   
}
